language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  -SECRET=111112222233333
  -NODE_ENV=development
  -DATABASE_URL=postgres://xdplmqap:wsGylY7JdrpJHf2OsqjtfA7RVrkfOBGT@isilo.db.elephantsql.com:5432/xdplmqap

after_success: npm run coverage

